input_vcf: 'test_trio.vcf.gz'
aaf_change: '0.9'
family_name: ['family_1', 'family_2']
ped: 'test_trio.ped'
pick: 'canonical'
samtools_version: 'samtools/1.9'
ref_genome: '/data/OGVFB/resources/1000G_phase2_GRCh37/human_g1k_v37_decoy.fasta'
VEP_version: 'VEP/96'
vcfanno_version: 'vcfanno/0.2.9'
vcfanno_lua: '/home/$USER/git/variant_prioritization/src/vcfanno_custom.lua'
vcfanno_conf: '/home/$USER/git/variant_prioritization/src/vcfanno_v4.conf'
vcf2db_version: 'vcf2db/2017.12.11'
gemini_version: 'gemini/0.20.1'
peddy_version: 'peddy/0.3.1'
python2_version: 'python/2.7'
R_version: 'R/3.5'
vt_version: 'vt/0.577'
spliceai_version: 'spliceai/20190507'
VCF-kit_version: 'VCF-kit/0.1.6'
annovar_version: 'annovar/2018-04-16'
InterVar_version: 'intervar/2.1.2'
intervar_evidence: '/data/OGVFB/OGL_NGS/OGL.variants.evidence.txt'
intervar_Rscript_path: '/home/$USER/git/variant_prioritization/src/intervar_v1.6.R'
pandoc_version: 'pandoc/2.1.1'
gemini_lenient: 'Yes'
output_raw: 'Yes'
SeeGEM_script: '/home/$USER/git/variant_prioritization/src/GEMINI_db_to_SeeGEM.R'
regions: '/home/$USER/git/variant_prioritization/src/vcf_region_split_1_coords.txt'
#regions, 1 for panel (only 1,2,..,22,x,y)
#regions, 25 or 100 for WGS of 50 cases.
#quotation marks can be single or double 
